#!/usr/bin/env bash
set -e

DEVCONTAINER_FILE=".devcontainer/devcontainer.json"

if [ ! -f "$DEVCONTAINER_FILE" ]; then
  echo "No .devcontainer/devcontainer.json found"
  exit 1
fi

BASE_IMAGE=$(jq -r '.image' "$DEVCONTAINER_FILE")
REMOTE_USER=$(jq -r '.remoteUser // "user"' "$DEVCONTAINER_FILE")
[[ "$REMOTE_USER" == "null" || -z "$REMOTE_USER" ]] && REMOTE_USER="user"

if [ "$BASE_IMAGE" = "null" ]; then
  echo "No 'image' field found in devcontainer.json"
  exit 1
fi

mkdir -p build/.devcontainer
WS_DIR=build/.devcontainer

cp ~/.vim/devcontainer/Dockerfile.extend "$WS_DIR/"

# Генерируем новый devcontainer.json
jq \
  --arg baseImage "$BASE_IMAGE" \
  --arg remoteUser "$REMOTE_USER" \
  '
  del(.image)
  + {
      build: {
        dockerfile: "Dockerfile.extend",
        args: {
          BASE_IMAGE: $baseImage
        }
      },
      mounts: (
        (.mounts // []) + [
          "source=${localEnv:HOME}/.vim/ls-settings/clangd-config/.config/clangd,target=/home/'$REMOTE_USER'/.config/clangd,type=bind,readonly",
          "source=${localEnv:HOME}/.vim/ls-settings/clangd-config/.clang-format,target=/home/'$REMOTE_USER'/.clang-format,type=bind,readonly",
          "source=${localEnv:HOME}/.vim/ls-settings/clangd-config/.clang-tidy,target=/home/'$REMOTE_USER'/.clang-tidy,type=bind,readonly",
          
          "source=${localEnv:HOME}/.vimrc,target=/home/'$REMOTE_USER'/.vimrc,type=bind,readonly",
          "source=${localEnv:HOME}/.vim,target=/home/'$REMOTE_USER'/.vim,type=bind,readonly",
          "source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind,readonly",
          
          "source=${localEnv:HOME}/.tmux.conf,target=/home/'$REMOTE_USER'/.tmux.conf,type=bind,readonly",
          
          "source=${localEnv:HOME}/.codeium,target=/home/'$REMOTE_USER'/.codeium,type=bind",
          
          "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind"
        ]
      ),
      containerEnv: (
          (.containerEnv // {}) + {
             "DISPLAY": "${localEnv:DISPLAY}",
             "TERM": "${localEnv:TERM}",
             "LANG": "C.UTF-8",
             "LC_ALL": "C.UTF-8"
          }
      ),
      runArgs: (
        (.runArgs // []) + [
          "-p", "8080",
          "--dns", "8.8.8.8",
          "--dns", "8.8.4.4"
        ]
      )
    }
  ' \
  "$DEVCONTAINER_FILE" > "$WS_DIR/devcontainer.json"
       #,
      #postAttachCommand: (
        #if .postAttachCommand then
          #.postAttachCommand + " && cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON || true"
        #else
          #"cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON || true"
        #end
      #)
      # Это было после runArgs, но я решил убрать, т. к. долго, + плохо работает (почему-то зависимости не подсасываются)
      
ls "$WS_DIR" -a
cat "$WS_DIR/devcontainer.json"

devcontainer up \
  --workspace-folder . \
  --config "$WS_DIR/devcontainer.json"

echo ""
echo -e "\033[0;32mDevcontainer successfuly started:\033[0m"
echo ""

devcontainer exec \
  --workspace-folder . \
  --config "$WS_DIR/devcontainer.json" \
  bash

