#!/bin/bash

templates_dir="$HOME/.local/templates"

if [ -f ./.clang-tidy ]; then
    echo ""
    echo "Команда init-clangd:"
    echo "Предупреждение .clang-tidy уже существует, копирование шаблонного не произошло!"
    echo ""
else
    cp "$templates_dir"/.clang-tidy .
    
    if [[ "$?" -ne 0 ]]; then
      echo ""
      echo "Команда init-clangd:"
      echo "Ошибка во время копирования шаблонного .clang-tidy"
      echo ""
    fi
fi

if [ -f ./.clang-format ]; then
    echo ""
    echo "Команда init-clangd:"
    echo "Предупреждение .clang-format уже существует, копирование шаблонного не произошло!"
    echo ""
else
    cp "$templates_dir"/.clang-format .
    
    if [[ "$?" -ne 0 ]]; then
      echo ""
      echo "Команда init-clangd:"
      echo "Ошибка во время копирования шаблонного .clang-format"
      echo ""
    fi
fi

if [ -f ./.clangd ]; then
    echo ""
    echo "Команда init-clangd:"
    echo "Предупреждение .clangd уже существует, копирование шаблонного не произошло!"
    echo ""
else
    cp "$templates_dir"/.clangd .

    if [[ "$?" -ne 0 ]]; then
      echo ""
      echo "Команда init-clangd:"
      echo "Ошибка во время копирования шаблонного .clangd"
      echo ""
    fi
fi

