#!/bin/bash

templates_dir="$HOME/.local/templates"

cp -f "$templates_dir"/.clang-tidy .
  if [[ "$?" -ne 0 ]]; then
      echo ""
      echo "Команда init-clangd:"
      echo "Ошибка во время копирования шаблонного .clang-tidy"
      echo ""
  fi

cp -f "$templates_dir"/.clang-format .
  if [[ "$?" -ne 0 ]]; then
      echo ""
      echo "Команда init-clangd:"
      echo "Ошибка во время копирования шаблонного .clang-format"
      echo ""
  fi

