# Переместить статусную строку наверх
set -g status-position top
setw -g window-status-current-style fg=black,bg=white

# Уменьшаем время выхода из режима по кнопке escape (полезно в vim - убирает ненужную задержку)
set -g escape-time 10

# Начинать нумерацию окон с 1
set -g base-index 1

# Начинать нумерацию панелей (splits) тоже с 1
setw -g pane-base-index 1

# Автоматически перенумеровывать окна при закрытии одного из них
set -g renumber-windows on

# Включаем поддержку 256 цветов
set -g default-terminal "xterm-256color"

# Разрешаем tmux передавать настройки цвета внешнему терминалу
set -as terminal-overrides ",xterm*:Tc"

# Разрешить программам внутри tmux менять заголовок окна
set -g allow-rename on

# Обновлять заголовок окна терминала на основе активной панели
set -g set-titles on
set -g set-titles-string '#T'   # #T = текущее название окна в tmux

# Основное: включает прокрутку мышью и работу с панелями
set -g mouse on

# Решает проблему с обрезанием вывода: увеличивает буфер истории до 10 000 строк
set -g history-limit 10000

# Перемещение между панелями как в Vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Опционально: изменение размера панелей (Alt + hjkl)
bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5
bind -n M-l resize-pane -R 5

